# Pydantic models for data validation
# This defines the "shape" of our data. Using Pydantic models ensures that the API only accepts and returns strictly formatted data.

from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    """What the user sends to our API."""
    query: str = Field(..., description="The question or prompt for the agent.", example="Explain quantum computing in one sentence.")

class ChatResponse(BaseModel):
    """What our API returns to the user."""
    answer: str = Field(..., description="The response generated by the LangChain agent.")